from datetime import date

from app.github.models import CollectedGitHubSignals, CommitSignal, RepositorySignal
from app.github.scoring import DeterministicScoreCalculator


def test_calculator_scores_only_2026_public_signals_deterministically() -> None:
    signals = CollectedGitHubSignals(
        username="Naseem9brev",
        repositories=[
            RepositorySignal(
                owner="Naseem9brev",
                name="Prompt2Ship",
                ai_dependency_hits=["openai"],
                ai_config_hits=[".cursorrules"],
            ),
            RepositorySignal(owner="Naseem9brev", name="private-shadow", is_public=False),
            RepositorySignal(owner="Naseem9brev", name="plain-public"),
        ],
        commits=[
            CommitSignal(
                sha="a",
                repository="Prompt2Ship",
                authored_at=date(2026, 1, 2),
                ai_attribution_markers=["co-authored-by: copilot"],
            ),
            CommitSignal(
                sha="b",
                repository="Prompt2Ship",
                authored_at=date(2026, 2, 3),
                generated_path_hits=["src/generated/client.ts"],
            ),
            CommitSignal(sha="c", repository="plain-public", authored_at=date(2026, 3, 4)),
            CommitSignal(sha="d", repository="plain-public", authored_at=date(2026, 4, 5)),
            CommitSignal(
                sha="e",
                repository="Prompt2Ship",
                authored_at=date(2025, 12, 31),
                ai_keyword_markers=["generated by ai"],
            ),
        ],
    )

    first = DeterministicScoreCalculator().calculate(signals)
    second = DeterministicScoreCalculator().calculate(signals)

    assert first == second
    assert first.score == 45
    assert first.repository_count == 2
    assert first.commit_count == 4
    assert {component.name: component.points for component in first.components} == {
        "commit_ai_markers": 20,
        "generated_code_surface": 5,
        "repository_ai_markers": 15,
        "tooling_depth": 5,
    }


def test_calculator_returns_zero_for_empty_public_history() -> None:
    score = DeterministicScoreCalculator().calculate(
        CollectedGitHubSignals(username="Naseem9brev", repositories=[], commits=[])
    )

    assert score.score == 0
    assert score.confidence == "low"
    assert score.repository_count == 0
    assert score.commit_count == 0
