from fastapi.testclient import TestClient

from app.main import app

client = TestClient(app)


def test_scan_contract_endpoint_returns_foundation_contract() -> None:
    response = client.get("/api/github/scan-contract?username=Naseem9brev")

    assert response.status_code == 200
    payload = response.json()
    assert payload["username"] == "Naseem9brev"
    assert payload["year"] == 2026
    assert "GET /repos/{owner}/{repo}/commits" in payload["rest_endpoints"]


def test_scan_endpoint_stub_accepts_request_without_auth_or_storage() -> None:
    response = client.post("/api/github/scans", json={"username": "Naseem9brev"})

    assert response.status_code == 202
    payload = response.json()
    assert payload["scan_id"].startswith("stub-")
    assert payload["status"] == "queued"
    assert payload["username"] == "Naseem9brev"
    assert "pending" in payload["message"]


def test_scan_status_endpoint_stub_is_storage_ready_contract() -> None:
    response = client.get("/api/github/scans/stub-123")

    assert response.status_code == 200
    assert response.json() == {
        "scan_id": "stub-123",
        "status": "stub",
        "message": "Scan status endpoint stub is ready for future storage-backed progress updates.",
    }


def test_score_preview_endpoint_uses_deterministic_calculator() -> None:
    response = client.post(
        "/api/github/scores/preview",
        json={
            "username": "Naseem9brev",
            "year": 2026,
            "repositories": [
                {
                    "owner": "Naseem9brev",
                    "name": "Prompt2Ship",
                    "ai_dependency_hits": ["openai"],
                    "ai_config_hits": [".cursorrules"],
                }
            ],
            "commits": [
                {
                    "sha": "abc",
                    "repository": "Prompt2Ship",
                    "authored_at": "2026-06-01",
                    "ai_keyword_markers": ["generated by ai"],
                    "generated_path_hits": ["app/generated/client.ts"],
                }
            ],
        },
    )

    assert response.status_code == 200
    payload = response.json()
    assert payload["score"] == 100
    assert payload["confidence"] == "low"
    assert payload["repository_count"] == 1
    assert payload["commit_count"] == 1
